# keep the order of agents aligned with the implementation

from tournament.agents.axelrod_first import (
    Davis,
    Downing,
    Feld,
    Graaskamp,
    Grofman,
    Grudger,
    Joss,
    Nydegger,
    Shubik,
    SteinAndRapoport,
    TidemanAndChieruzzi,
    Tullock,
)
from tournament.agents.axelrod_second import (
    Borufsen,
    Champion,
    Leyvraz,
    SecondByBlackK83R,
    SecondByCave,
    SecondByGraaskampKatzen,
    SecondByHarrington,
    SecondByTidemanAndChieruzzi,
    SecondByWeiner,
    SecondByWhiteK72R,
    SecondByWmAdams,
)
from tournament.agents.constant import AllC, AllD
from tournament.agents.pavlov import Pavlov
from tournament.agents.random import RandomAgent
from tournament.agents.tft import (
    TFTT,
    TTFT,
    GenerousTFT,
    GradualTFT,
    OmegaTFT,
    TitForTat,
)

AGENTS = [
    AllC,
    AllD,
    TitForTat,
    RandomAgent,
    Pavlov,
    OmegaTFT,
    TFTT,
    TTFT,
    GradualTFT,
    GenerousTFT,
    Davis,
    # Graaskamp,
    Shubik,
    SteinAndRapoport,
    Grudger,
    TidemanAndChieruzzi,
    Nydegger,
    Grofman,
    Tullock,
    Downing,
    Joss,
    Feld,
    Champion,
    Borufsen,
    Leyvraz,
    SecondByHarrington,
    SecondByWhiteK72R,
    SecondByBlackK83R,
    SecondByTidemanAndChieruzzi,
    SecondByWmAdams,
    SecondByCave,
    SecondByGraaskampKatzen,
    SecondByWeiner,
]
